name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
        # run build and test           
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test MSTest
        run: dotnet test ManagedCode.TestsDetector.MSTest/ManagedCode.TestsDetector.MSTest.csproj
      - name: Test NUnit
        run: dotnet test ManagedCode.TestsDetector.MSTest/ManagedCode.TestsDetector.NUnit.csproj
      - name: Test XUnit
        run: dotnet test ManagedCode.TestsDetector.MSTest/ManagedCode.TestsDetector.XUnit.csproj
    